server:
  port: 4004 # Gateway listens on port 4004

spring:
  cloud:
    gateway:
      routes:
        # http://localhost:4004/auth/login -> http://auth-service:4005/login
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/** # Match /auth/** path
          filters:
            - StripPrefix=1 # Remove /api from the path

        # Route for /api/patients/** to patient-service
        # Rest Client -> http://localhost:4004/api/patients/**
        # Api Gateway -> http://patient-service:4000/**
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/** # Match /api/patients/** path
          filters:
            - StripPrefix=1 # Remove /api from the path
            - JwtValidation # Validate JWT token - JwtValidation-GatewayFilterFactory

        # Route for /api/docs/patients to patient-service /v3/api-docs
        # Rest Client -> http://localhost:4004/api/docs/patients
        # Api Gateway -> http://patient-service:4000/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs